config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'
  
  resources :artists do
    resources :songs
  end
  
  resources :billboards do
    resources :songs
  end
  
end

# root 'artists#index'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs, dependent: :destroy
    # dependent destroy
end

app/models/billboard.rb
class Billboard < ApplicationRecord
    has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :artist
    belongs_to :billboard
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :update, :edit, :destroy]
  
  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
    render partial: "form"
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else 
      render :edit
    end
  end

  def edit 
    render partial: "form"
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else 
      render :new
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private
    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name, :logo)
    end
  

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :edit, :update, :destroy]
  # before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index 
    @billboards = Billboard.all
  end
  
  def show
  end

  def new
    @billboard = Billboard.new
    render partial: 'form'
  end
  
  def update
    if  @billboard.update(billboard_params)
      redirect_to @billboard
    else 
      render :edit
    end
  end

  def edit
    render partial: 'form'
  end


  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save 
      redirect_to billboards_path
    else 
      render :new
    end
  end
  

  def destroy
    @billboard.destroy
  end
    

  private 

    def set_billboard
      @billboard = Billboard.find(params[:id])
    end

    def billboard_params
      params.require(:billboard).permit(:name)
    end
    
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  
  def index
    @songs = @artist.songs.all
  end
  
  def show
  end
  
  def new
    @song = @artist.songs.new

    render partial: 'form'
  end
  
  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to artist_songs_path
    else 
      render :new
    end
  end
  
  def update
    if @artist.update(song_params)
      redirect_to [@artist, @song]
    else 
      render :edit
    end
  end

  def edit
    render partial: 'form'
  end
  
  def destroy
    @song.destroy
    redirect_to artist_songs_path
  end

  private
  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:name, :song_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? 'Change Artist' : 'Add Artist' %></h1>
<hr />
<%= form_with(model: @artist, local: true, class: "ui form") do |f| %>
  <div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%# <%= f.label :logo %>
  <%# <%= f.text_field %>
  <%= f.submit %>
  </div>
<% end %>

app/views/artists/index.html.erb
<h1 class="ui header">Add an Artist</h1>
<%= link_to 'Add an Artist', new_artist_path %>
<ul>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, artist_path(artist) %></li>
  <% end %>
</ul>

app/views/artists/show.html.erb
<div class="ui card">
    <div class="content">
    <h1><%= @artist.name %></h1>
    </div>
    <hr />
    <div class="extra content">
    <p>What would you like to do?</p>
    <%= link_to 'View Songs', artist_songs_path(@artist) %> |
    <br />
    <%= link_to 'Edit Artist', edit_artist_path(@artist) %> |
    <br />
    <%= link_to 'Erase Artist', @artist, method: :delete %> |
    <%= link_to 'Back', artists_path %> |
    </div>
</div>

app/views/billboards/_form.html.erb
<h1><%= @billboard.id ? 'Edit billboard' : 'Create billboard' %></h1>
<hr />
<%= form_for [@song, @billboard] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/billboards/index.html.erb
<h1>Billboards</h1>
<%= link_to 'Create Billboard', new_billboard_path %>
<ul>
    <% @billboards.each do |billboard| %>
      <li> <%= link_to billboard.name, billboard_path(billboard) %>
      </li>
    <% end %>
</ul>

app/views/billboards/show.html.erb
<h1><%= @billboard.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Songs', billboard_songs_path(@billboard) %>
<br />
<%= link_to 'Change Billboard', edit_billboard_song_path(@billboard) %>
<br />
<%= link_to 'Erase Billboard', @billboard, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillboardApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui-container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/songs/_form.html.erb
<h1><%= @song.id ? 'Edit Song' : 'Create Song' %></h1>
<hr />
<%= form_for [@artist, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%#= f.select “@billboards_id”, options_for_select(@billboards.collect {|u| [u.name, u.id] },{:include_blank => true}) %>
  <br />
  <%= f.submit %>
<% end %>

app/views/songs/index.html.erb
<h1>View Songs</h1>
<%= link_to 'Create a new song', new_artist_song_path(@artist) %>
<ul>
  <% @songs.each do |song| %>
    <li><%= link_to song.name, [@artist, song] %></li>
  <% end %>
</ul>

app/views/songs/show.html.erb
<h1><%= @artist.name %> - <%= @song.name %></h1>
<p><%= @artist.songs %></p>
<%= link_to 'Edit Song', edit_artist_song_path([@artist, @song]) %>
<%= link_to 'Delete Song', [@artist, @song], method: :delete %>
<%= link_to 'Back To Songs', artist_songs_path(@artist) %>
<%= link_to 'Back to Artist', root_path %>
<%= link_to 'Billboards', billboards_path(@billboard) %>
<%#= f.select “@billboards_id”, options_for_select(@billboards.collect {|u| [u.name, u.id] },{:include_blank => true}) %>